package com.stxnext.stxinsider.constant

import android.text.SpannableString
import com.stxnext.stxinsider.view.model.DetailsItem

/**
 * Created by bkosarzycki on 17.02.16.
 */
object EventsData2016 {

    val data : List<DetailsItem<SpannableString>> = listOf(
            DetailsItem<SpannableString>("Wacław Zalewski & Henk van Leussen", "Presentation additional info", "teams/events/stx2016/row_0.jpg",
                    SpannableString("<b>Abstract:</b> <br/> <br/> As nearshoring and outsourcing are becoming increasingly important components of the modern economy, we would like to address opportunities and business value Central European partners can provide. We we'll also discuss the current practice and share our thoughts on the future of this type of cooperation. <br/> <br/> <b>Wacław <br/> <br/> Bio: <br/> <br/> </b> Wacław having the pleasure of leading the magnificent Business Research Team, my responsibilities include, but are not limited to, prospecting, lead generation, CRM management and finding a way to get in touch with decision makers you need. I'm also unable to write about myself in third person.  <br/> <br/> <b>Henk <br/> <br/>  Bio: </b> <br/> <br/>  In my job, VP of Business Development, I’m managing all phases of business development, business planning, prospecting, building C-level relationships, detailed presentations and negotiations to closing and follow-up. I’m well in improving (administrative) processes, have a creative mind, think in solutions and may well convince. <br/> <br/>")),
            DetailsItem<SpannableString>("Radosław Jankiewicz", "Presentation additional info", "teams/events/stx2016/row_1.jpg",
                    SpannableString("<b>Abstract: </b> <br/> <br/>  Discovering React JS library completely changed my opinion about development of client-side applications. In my presentation I'd like to give a short and comprehensive introduction to React JS and share my impressions about it. I hope my talk will convince those who haven't had a chance to use React JS to give it a try. <br/> <br/>  <b> Bio: </b> <br/> <br/> Radek is a Python programmer who recently got an opportunity to get involved into developing a real-time updated client-side application with JavaScript. He has been related with STXNext for almost a decade")),
            DetailsItem<SpannableString>("Coffee time!", "",  "teams/events/stx2016/row_2.png", SpannableString("")),
            DetailsItem<SpannableString>("Tomasz Muszczek & Piotr Błaszczyk", "Presentation additional info", "teams/events/stx2016/row_3.jpg",
                    SpannableString("<b>Abstract:  </b> <br/> <br/> Some time ago we introduced test automation in our project, at UI as well as API level. We would like to share our thoughts, experiences and overall encourage other QAs to adapt automation also in their projects. We are going to show the disadvantages of manual testing, how testing can be improved with automation and present the automated tests in action using some public API. <br/> <br/> <b>Tomasz <br/> <br/> Bio: </b> <br/> <br/> I've been working for STX Next for a year and a half now and so far it's been a great adventure. At the moment I'm a software tester in the largest project in our office in Piła, however I want to become a Product Owner. Working in international environment is very exciting, but also very demanding and for this reason whenever I can I jump on my motorcycle and relax riding on two wheels. <br/> <br/> <b> Piotr <br/> <br/> Bio: </b> <br/> <br/> I have worked in STX for over a year now.  I consider the last year of my work to be the most fruitful one in terms of self-development. I am a member of NCL project. After hours, I usually spend my time playing football and role-playing games.")),
            DetailsItem<SpannableString>("Paweł Jurdeczka", "Presentation additional info", "teams/events/stx2016/row_4.jpg", SpannableString("<b>Abstract: </b> <br/> <br/> My talk is a kind of summary of 7 my years experience in projects for brands like Pepsi, T-mobile, Sanitec Kolo, BZ WBK, Carry, Enea, Hogarth Worldwide. I will talk about finding a pattern in fixing challenging and failing projects. <br/> <br/>  <b>Bio: </b> <br/> <br/> I am a Product Owner with a pinch of UX designer, marketer and entrepreneur. In STX mainly focused on communicating complex ideas in a simple and accessible manner. Passionate about sketch noting, validated learning and Lean Startup movement.")),
            DetailsItem<SpannableString>("Rafał Gajewski", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("<b> Abstract: </b> <br/> <br/> My talk is about mobile trends and how mobile team can help you create the mobile applications. I am going also present our mobile team and stand. <br/> <br/> <b>Bio: </b> <br/> <br/>  Project Manager, Scrum Master, Entrepreneur, was creating some of Startups. Actually VP of Mobile Engineering in STX Next where is helping their customers to create the vision of mobile application from scratch and help to build the perfect team which deliver the apps. ")),
            DetailsItem<SpannableString>("Lunch time!", "",  "teams/events/stx2016/row_2.jpg",SpannableString("")),
            DetailsItem<SpannableString>("Łukasz Aziukiewicz", "Presentation additional info",  "teams/events/stx2016/row_7.jpg",SpannableString("<b>Abstract: </b> <br/> <br/>  Scaling Scrum is a very hot topic recently and several frameworks have been built around this issue. Sometimes when you're working with just 3-4 teams they might seem overwhelming and add too much overhead though. During my talk I'll share some of my experiences with lightweight scrum scaling that you can apply in your projects. <br/> <br/> <b>Bio: </b> <br/> <br/>  Scrum Master and Agile Coach involved in company agile transformation and mentoring less experiences Scrum Masters as well as people interested in this role. Łukasz has been working using agile software development for the last few years, building effective teams in various organizations.")),
            DetailsItem<SpannableString>("Tomasz Maćkowiak", "Presentation additional info",  "teams/events/stx2016/row_8.jpg",SpannableString("<b>Abstract: </b> <br/> <br/> Promises are a new JavaScript API for dealing with deferred execution. The lecture will introduce the listener to the concept of Promises, show their applications and encourage to try them out. And as a bonus the listener might learn some shocking revelations about the JavaScript event loop! <br/> <br/> <b>Bio: </b> <br/> <br/> Tomasz is working in STX Next since 2007. Fullstack developer fluent in both Python and JavaScript. Lecturer at post-grad Python studies and many internal workshops within STX. One can see him giving presentations at PyRa, PyconPL and STX Lighting Talks. Fan of programming riddles.")),
            DetailsItem<SpannableString>("Coffee time!", "",  "teams/events/stx2016/row_2.png", SpannableString("")),
            DetailsItem<SpannableString>("Dominik Oślizło", "Presentation additional info",  "teams/events/stx2016/row_10.jpg",SpannableString("<b>Abstract: </b> <br/> <br/>  During my presentation, I will tell how to shape cooperation between a Client and a Software House to make a digital product successful in three main aspects: return over investment, value for the users and technology. <br/> <br/> <b>Bio: </b> <br/> <br/> UX is not, and will never be, an isolated discipline. Rather than that, it is a universal mindset of creation and improvement, applicable to design, programming, web, marketing, strategy, advertising, and most importantly: to business. I apply this principle at my work, to make business, design and technology work better together. ")),
            DetailsItem<SpannableString>("Łukasz Koczwara", "Presentation additional info",  "teams/events/stx2016/row_11.jpg",SpannableString("<b>Abstract: </b> <br/> <br/>  Quick talk about managing technical debt, useful software metrics and transparency in software development. You will get a unique chance to learn how to make your software project transparent and visualize all the risk hidden behind different quality issues with the help of SonarQube and Seerene tooling. <br/> <br/> <b>Bio: </b> <br/> <br/> I am a software development manager experienced in team leading and managing projects. However, I still try to find few hours for pure coding fun because I really think best IT managers derive from decent technical environments. As a software quality consultant I conducted multiple code quality audits for customers from all industry branches and I also did few workshops in Germany, France and England on the topic of software development best practices and software quality assurance.")),
            DetailsItem<SpannableString>("Maciej Dziergwa", "Presentation additional info",  "teams/events/stx2016/row_12.jpg",SpannableString("<b>Abstract: </b> <br/> <br/>  Today I will tell about our plans for 2016 also share some news about the STX Next. <br/> <br/> <b>Bio: </b> <br/> <br/> CEO of STX Next. Maciej started his career as a Python Developer in a Dutch company, but shortly after returned to Poland where he founded his own company, now known as STX Next. As CEO, he leads a team of over 110 Python, mobile & front-end developers. He is responsible for executing the strategic direction and ongoing operations, growing Software House business worldwide.")),
            DetailsItem<SpannableString>("Break!", "",  "teams/events/stx2016/row_2.png",SpannableString("")),
            DetailsItem<SpannableString>("Banquet", "",  "teams/events/stx2016/row_14.jpg",SpannableString(""))

    )
}