package com.stxnext.stxinsider.constant

import android.text.SpannableString
import com.stxnext.stxinsider.view.model.DetailsItem

/**
 * Created by bkosarzycki on 17.02.16.
 */
object EventsData2016 {

    val data : List<DetailsItem<SpannableString>> = listOf(
            DetailsItem<SpannableString>("Wacław Zalewski & Henk van Leussen", "Presentation additional info", "teams/events/stx2016/row_0.jpg",
                    SpannableString("<b>Abstract:</b> <br/> <br/> As nearshoring and outsourcing are becoming increasingly important components of the modern economy, we would like to address opportunities and business value Central European partners can provide. We we'll also discuss the current practice and share our thoughts on the future of this type of cooperation. <br/> <br/> <b>Wacław <br/> <br/> Bio: <br/> <br/> </b> Wacław having the pleasure of leading the magnificent Business Research Team, my responsibilities include, but are not limited to, prospecting, lead generation, CRM management and finding a way to get in touch with decision makers you need. I'm also unable to write about myself in third person.  <br/> <br/> <b>Henk <br/> <br/>  Bio: </b> <br/> <br/>  In my job, VP of Business Development, I’m managing all phases of business development, business planning, prospecting, building C-level relationships, detailed presentations and negotiations to closing and follow-up. I’m well in improving (administrative) processes, have a creative mind, think in solutions and may well convince. <br/> <br/>")),
            DetailsItem<SpannableString>("Radosław Jankiewicz", "Presentation additional info", "teams/events/stx2016/row_1.jpg",
                    SpannableString("<b>Abstract: </b> <br/> <br/>  Discovering React JS library completely changed my opinion about development of client-side applications. In my presentation I'd like to give a short and comprehensive introduction to React JS and share my impressions about it. I hope my talk will convince those who haven't had a chance to use React JS to give it a try. <br/> <br/>  <b> Bio: </b> <br/> <br/> Radek is a Python programmer who recently got an opportunity to get involved into developing a real-time updated client-side application with JavaScript. He has been related with STXNext for almost a decade")),
            DetailsItem<SpannableString>("Coffee time!", "",  "teams/events/stx2016/row_2.png", SpannableString("")),
            DetailsItem<SpannableString>("Tomasz Muszczek & Piotr Błaszczyk", "Presentation additional info", "teams/events/stx2016/row_3.jpg",
                    SpannableString("<b>Abstract:  </b> <br/> <br/> Some time ago we introduced test automation in our project, at UI as well as API level. We would like to share our thoughts, experiences and overall encourage other QAs to adapt automation also in their projects. We are going to show the disadvantages of manual testing, how testing can be improved with automation and present the automated tests in action using some public API. <br/> <br/> <b>Tomasz <br/> <br/> Bio: </b> <br/> <br/> I've been working for STX Next for a year and a half now and so far it's been a great adventure. At the moment I'm a software tester in the largest project in our office in Piła, however I want to become a Product Owner. Working in international environment is very exciting, but also very demanding and for this reason whenever I can I jump on my motorcycle and relax riding on two wheels. <br/> <br/> <b> Piotr <br/> <br/> Bio: </b> <br/> <br/> I have worked in STX for over a year now.  I consider the last year of my work to be the most fruitful one in terms of self-development. I am a member of NCL project. After hours, I usually spend my time playing football and role-playing games.")),
            DetailsItem<SpannableString>("Paweł Jurdeczka", "Presentation additional info", "teams/events/stx2016/row_4.jpg", SpannableString("<b>Abstract: </b> <br/> <br/> My talk is a kind of summary of 7 my years experience in projects for brands like Pepsi, T-mobile, Sanitec Kolo, BZ WBK, Carry, Enea, Hogarth Worldwide. I will talk about finding a pattern in fixing challenging and failing projects. <br/> <br/>  <b>Bio: </b> <br/> <br/> I am a Product Owner with a pinch of UX designer, marketer and entrepreneur. In STX mainly focused on communicating complex ideas in a simple and accessible manner. Passionate about sketch noting, validated learning and Lean Startup movement.")),
            DetailsItem<SpannableString>("Name Surname", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("Some spannable content <b> bold content </b>")),
            DetailsItem<SpannableString>("Name Surname", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("Some spannable content <b> bold content </b>")),
            DetailsItem<SpannableString>("Name Surname", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("Some spannable content <b> bold content </b>")),
            DetailsItem<SpannableString>("Name Surname", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("Some spannable content <b> bold content </b>")),
            DetailsItem<SpannableString>("Name Surname", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("Some spannable content <b> bold content </b>")),
            DetailsItem<SpannableString>("Name Surname", "Presentation additional info",  "teams/events/stx2016/row_5.jpg",SpannableString("Some spannable content <b> bold content </b>"))

    )
}